<#
.SYNOPSIS
    Generate the WiX authoring for the skill payload.

.DESCRIPTION
    WaterFreeInstaller.wxs used to declare a Directory/Component/ComponentRef
    triple per skill by hand. The list drifted twice: waterfree-assets,
    waterfree-imagegen and waterfree-vision were never laid down under
    INSTALLDIR\skills, and waterfree-qa joined them when it was added. The
    installer helper only enumerates directories that actually exist there, so
    a skill missing from the list is silently never installed -- the build
    stays green and the feature just is not there.

    It also only ever shipped SKILL.md per skill, so waterfree-assets would
    have arrived without any of its nine bin/*.py scripts even once it was
    listed.

    This script walks the staged payload and emits one component per file,
    directories and all, so a new skill needs no installer edit at all.

.PARAMETER PayloadSkillsDir
    The staged skills tree (installer\obj\payload\skills), already populated by
    the wixproj's BuildPayload target.

.PARAMETER OutputFile
    The .wxs fragment to write.

.PARAMETER PayloadVariable
    Name of the WiX preprocessor variable holding the payload root, so the
    generated Source attributes match the hand-written authoring.

.NOTES
    Component GUIDs are derived deterministically from the file's install path
    (see New-DeterministicGuid). They must be stable across builds: Windows
    Installer identifies a component by its GUID, and a GUID that changed every
    build would break repair and uninstall reference counting. Guid="*" would
    also work, but only for components whose keypath is a file -- and these use
    an HKCU registry keypath, which is the correct shape for a perUser package.
#>

param(
    [Parameter(Mandatory)][string]$PayloadSkillsDir,
    [Parameter(Mandatory)][string]$OutputFile,
    [string]$PayloadVariable = "var.PayloadDir",
    [string]$ParentDirectoryId = "SkillsDir",
    [string]$ComponentGroupId = "SkillComponents"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# Fixed namespace. Changing this re-GUIDs every skill component, so do not.
$GuidNamespace = "WaterFree.Skills.v1"

function New-DeterministicGuid([string]$key) {
    <#
    Same key in, same GUID out, on every machine and every build. MD5 is used
    as a hash here, not as a security primitive: the input is a relative file
    path chosen by us, so collision resistance is not the property we need.
    #>
    $md5 = [System.Security.Cryptography.MD5]::Create()
    try {
        $bytes = $md5.ComputeHash([System.Text.Encoding]::UTF8.GetBytes("$GuidNamespace/$key"))
    } finally {
        $md5.Dispose()
    }
    # Stamp version 3 and the RFC 4122 variant so the result is a well-formed
    # name-based UUID rather than 16 arbitrary bytes wearing a GUID costume.
    $bytes[6] = [byte](($bytes[6] -band 0x0F) -bor 0x30)
    $bytes[8] = [byte](($bytes[8] -band 0x3F) -bor 0x80)
    return "{$(([guid]::new($bytes)).ToString().ToUpperInvariant())}"
}

function ConvertTo-WixId([string]$prefix, [string]$key) {
    <#
    WiX Ids allow [A-Za-z0-9_.] and must start with a letter or underscore.
    A hash suffix keeps them unique after sanitising, and keeps the total
    length inside the 72-character limit for long nested paths.
    #>
    $safe = ($key -replace '[^A-Za-z0-9_]', '_')
    $md5 = [System.Security.Cryptography.MD5]::Create()
    try {
        $hash = [System.BitConverter]::ToString(
            $md5.ComputeHash([System.Text.Encoding]::UTF8.GetBytes($key))
        ).Replace("-", "").Substring(0, 8)
    } finally {
        $md5.Dispose()
    }
    $maxBody = 72 - $prefix.Length - 1 - $hash.Length
    if ($safe.Length -gt $maxBody) { $safe = $safe.Substring(0, $maxBody) }
    return "$prefix$safe`_$hash"
}

function Get-RelativePath([string]$root, [string]$full) {
    $rootFull = [System.IO.Path]::GetFullPath($root).TrimEnd('\')
    $itemFull = [System.IO.Path]::GetFullPath($full)
    return $itemFull.Substring($rootFull.Length).TrimStart('\')
}

if (-not (Test-Path $PayloadSkillsDir)) {
    throw "Staged skills directory not found: $PayloadSkillsDir. The wixproj's BuildPayload target should have created it."
}

$skillRoots = @(Get-ChildItem -Path $PayloadSkillsDir -Directory |
    Where-Object { Test-Path (Join-Path $_.FullName "SKILL.md") } |
    Sort-Object Name)

if ($skillRoots.Count -eq 0) {
    # Never emit an empty fragment quietly: that is exactly the silent-drop
    # failure this script exists to prevent, just one level up.
    throw "No skill packages (directories containing SKILL.md) found under '$PayloadSkillsDir'."
}

$lines = [System.Collections.Generic.List[string]]::new()
$componentIds = [System.Collections.Generic.List[string]]::new()

$lines.Add('<?xml version="1.0" encoding="UTF-8"?>')
$lines.Add('<!-- GENERATED by installer\GenerateSkillComponents.ps1 - do not edit by hand. -->')
$lines.Add('<!-- Regenerated on every build from the staged skills payload, so a new     -->')
$lines.Add('<!-- skill directory needs no installer change to ship.                      -->')
$lines.Add('<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">')
$lines.Add('  <Fragment>')
$lines.Add("    <DirectoryRef Id=`"$ParentDirectoryId`">")

function Write-DirectoryTree([System.IO.DirectoryInfo]$dir, [int]$depth) {
    $indent = "  " * ($depth + 3)
    $relDir = Get-RelativePath $PayloadSkillsDir $dir.FullName
    $dirId = ConvertTo-WixId "sd_" $relDir

    $script:lines.Add("$indent<Directory Id=`"$dirId`" Name=`"$($dir.Name)`">")

    foreach ($file in (Get-ChildItem -Path $dir.FullName -File | Sort-Object Name)) {
        $relFile = Get-RelativePath $PayloadSkillsDir $file.FullName
        $componentId = ConvertTo-WixId "sc_" $relFile
        $fileId = ConvertTo-WixId "sf_" $relFile
        $guid = New-DeterministicGuid $relFile
        $source = "`$($PayloadVariable)\skills\$relFile"

        $script:lines.Add("$indent  <Component Id=`"$componentId`" Guid=`"$guid`">")
        $script:lines.Add("$indent    <File Id=`"$fileId`" Source=`"$source`" KeyPath=`"no`" />")
        # HKCU keypath, matching the hand-written components: a perUser package
        # reference-counts per user, and a file keypath under LocalAppData does
        # not give Windows Installer anything user-scoped to count.
        $script:lines.Add("$indent    <RegistryValue Root=`"HKCU`" Key=`"Software\WaterFree\Components`" Name=`"$componentId`" Type=`"string`" Value=`"1`" KeyPath=`"yes`" />")
        $script:lines.Add("$indent  </Component>")
        $script:componentIds.Add($componentId)
    }

    foreach ($child in (Get-ChildItem -Path $dir.FullName -Directory | Sort-Object Name)) {
        Write-DirectoryTree $child ($depth + 1)
    }

    # One component per directory carrying its RemoveFolder, so every directory
    # this package created is taken away again on uninstall. Without these the
    # skill folders are left behind empty.
    $removeComponentId = ConvertTo-WixId "sr_" $relDir
    $script:lines.Add("$indent  <Component Id=`"$removeComponentId`" Guid=`"$(New-DeterministicGuid "remove/$relDir")`">")
    $script:lines.Add("$indent    <RemoveFolder Id=`"$(ConvertTo-WixId 'srf_' $relDir)`" Directory=`"$dirId`" On=`"uninstall`" />")
    $script:lines.Add("$indent    <RegistryValue Root=`"HKCU`" Key=`"Software\WaterFree\Components`" Name=`"$removeComponentId`" Type=`"string`" Value=`"1`" KeyPath=`"yes`" />")
    $script:lines.Add("$indent  </Component>")
    $script:componentIds.Add($removeComponentId)

    $script:lines.Add("$indent</Directory>")
}

foreach ($skill in $skillRoots) {
    Write-DirectoryTree $skill 0
}

$lines.Add('    </DirectoryRef>')
$lines.Add('')
$lines.Add("    <ComponentGroup Id=`"$ComponentGroupId`">")
foreach ($id in $componentIds) {
    $lines.Add("      <ComponentRef Id=`"$id`" />")
}
$lines.Add('    </ComponentGroup>')
$lines.Add('  </Fragment>')
$lines.Add('</Wix>')

$newContent = ($lines -join "`r`n") + "`r`n"

# Only rewrite when something changed, so MSBuild does not see a fresh
# timestamp and rebuild the MSI on every no-op build.
$existing = if (Test-Path $OutputFile) { Get-Content -Path $OutputFile -Raw } else { $null }
if ($existing -ne $newContent) {
    $dir = Split-Path -Parent $OutputFile
    if ($dir -and -not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
    # utf8 without BOM would be nicer, but Windows PowerShell 5.1's -Encoding
    # utf8 writes a BOM and the WiX compiler is perfectly happy with one.
    Set-Content -Path $OutputFile -Value $newContent -Encoding utf8 -NoNewline
}

$skillNames = ($skillRoots.Name | Sort-Object) -join ", "
Write-Host "  Skill components: $($skillRoots.Count) skill(s) -> $(Split-Path -Leaf $OutputFile)"
Write-Host "    $skillNames"
